# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  This course builds on skills acquired in CSCI 150, placing emphasis on object-oriented
  software design and data abstraction. Students are introduced to data
  structures (lists, stacks, queues, trees, heaps, hash tables, graphs) and
  programming techniques such as recursion and sorting algorithms. Other topics
  include analysis of algorithm complexity, automated unit testing, and inheritance.
  Programming assignments focus on the design and implementation of algorithms
  and data structures using the Java language.
baseurl: "/csci151" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

number: CSCI 151
title: Data Structures
semester: Fall 2025
hypothesis: false

jumbotext: wikimedia CC BY 2.0
jumbourl: https://en.wikipedia.org/wiki/Crown_shyness#/media/File:River_of_Blue.jpg

navigation:
  - title: Overview
    subfolderitems:
      - page: Description
        url: '#description'
      - page: Learning Goals
        url: '#goals'
      - page: Resources
        url: '#resources'
  - page: In-Class Code
    url: '#inclasscode'
  - page: Calendar
    url: 'https://app.teamgantt.com/public/projects/calendar/?projectIds=4170796&publicKeys=S80tLK4hjmV7&ids=4170796'
  - title: Coursework
    subfolderitems:
      - page: Labs
        url: '#labs'
      - page: Formative Assessment
        url: '#hw'
      - page: Skills Projects
        url: '#projects'
      - page: Final Project
        url: '#finalproject'
      - page: Grading
        url: '#scale'
  - page: Commitments
    url: '#commitments'

instructors:
  - id: ferrer
    name: Dr. Gabriel Ferrer
    email: ferrer@hendrix.edu
    web: https://gjf2a.github.io/
    officehours: https://drferrer.youcanbook.me/
  - id: goadrich
    name: Dr. Mark Goadrich
    email: goadrich@hendrix.edu
    web: http://mark.goadrich.com/
    officehours: https://markgoadrich.youcanbook.me/

offerings:
  - name: LECTURE 01
    loc: MCReynolds 315
    time: MWF 10:10am - 11:00am
    instructor: ferrer
  - name: LAB 01
    loc: Snoddy Lab
    time: T 1:10pm - 4:00pm
    instructor: ferrer

resources:
  - name: Azul Zulu Java 21 LTS
    image: assets/images/java-logo.png
    url: https://www.azul.com/downloads/?version=java-21-lts&package=jdk-fx#zulu
  - name: IntelliJ IDEA Community Edition
    image: assets/images/IntelliJ_IDEA_Logo.png
    url: https://www.jetbrains.com/idea/
  - name: SceneBuilder 22
    image: assets/images/SceneBuilderLogo.png
    url: https://gluonhq.com/products/scene-builder/

extra-resources:
  - name: CS2Mulch
    image: assets/images/cs2mulch.png
    url: https://mgoadric.github.io/cs2mulch/
  - name: Algorithms
    image: assets/images/algorithms.png
    url: https://algs4.cs.princeton.edu/
  - name: CUVids
    image: assets/images/cuvids.png
    url: https://cuvids.io/app/course/2/

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
remote_theme: hendrix-cs/csci000
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
