# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  This course builds on skills acquired in CSCI 150, placing emphasis on object-oriented
  software design and data abstraction. Students are introduced to data
  structures (lists, stacks, queues, trees, heaps, hash tables, graphs) and
  programming techniques such as recursion and sorting algorithms. Other topics
  include analysis of algorithm complexity, automated unit testing, inheritance.
  Programming assignments focus on the design and implementation of algorithms
  and data structures using the Java language.
baseurl: "/csci151" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

number: CSCI 151
title: Data Structures
semester: Spring 2021

navigation:
  - title: Overview
    subfolderitems:
      - page: Description
        url: '#description'
      - page: Learning Goals
        url: '#goals'
      - page: Resources
        url: '#resources'
  - page: In-Class Code
    url: '#inclasscode'
  - page: Calendar
    url: https://prod.teamgantt.com/gantt/schedule/?ids=2460416&public_keys=1IYrgqc57ynw&zoom=d100&font_size=12&estimated_hours=0&assigned_resources=0&percent_complete=0&documents=0&comments=0&col_width=355&hide_header_tabs=0&menu_view=1&resource_filter=1&name_in_bar=0&name_next_to_bar=0&resource_names=1&resource_hours=1#user=&company=&custom=&date_filter=&hide_completed=false&color_filter=
  - title: Coursework
    subfolderitems:
      - page: Labs
        url: '#labs'
      - page: Homework
        url: '#hw'
      - page: Projects
        url: '#projects'
      - page: Exams
        url: '#exams'
      - page: Checkins
        url: '#checkins'
      - page: Scale
        url: '#scale'
  - page: Commitments
    url: '#commitments'

instructors:
  - id: yorgey
    name: Dr. Brent Yorgey
    email: yorgey@hendrix.edu
    web: http://ozark.hendrix.edu/~yorgey
    phone: (501) 450-1377
    officehours: https://byorgey.youcanbook.me
  - id: goadrich
    name: Dr. Mark Goadrich
    email: goadrich@hendrix.edu
    web: http://mark.goadrich.com
    officehours: http://markgoadrich.youcanbook.me

offerings:
  - name: LECTURE 01
    loc: MCAcxiom 119
    time: MWF 8:10am - 9:00am
    instructor: goadrich
  - name: LAB 01
    loc: Snoddy Lab / Microsoft Teams
    time: T 1:35pm - 4:25pm
    instructor: goadrich

resources:
  - name: Java
    image: assets/images/java-logo.png
    url: https://www.oracle.com/java/technologies/javase-jdk11-downloads.html
  - name: IntelliJ
    image: assets/images/IntelliJ_IDEA_Logo.png
    url: https://www.jetbrains.com/idea/
  - name: JavaFX
    image: assets/images/javafx.png
    url: https://openjfx.io/
  - name: SceneBuilder
    image: assets/images/SceneBuilderLogo.png
    url: https://gluonhq.com/products/scene-builder/

extra-resources:
#  - name: Java4Python
#    image: assets/images/runestone_logo.png
#    url: https://runestone.academy/runestone/books/published/java4python/index.html
#  - name: CodingBat Java
#    image: assets/images/codingbat.jpg
#    url: https://codingbat.com/
  - name: CS2Mulch
    image: assets/images/cs2mulch.png
    url: https://mgoadric.github.io/cs2mulch/
  - name: Algorithms
    image: assets/images/algorithms.png
    url: https://algs4.cs.princeton.edu/
  - name: CUVids
    image: assets/images/cuvids.png
    url: https://cuvids.io/app/course/2/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
